#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Author: Bryan Hu .

@Bryan Hu .

Made with love by Bryan Hu .


Version: stacksearch.__version__

Desc: The standalone version of StackSearch

"""
from sys import argv
from stacksearch import custom_main

custom_main(argv[1:])
